/** Stable, machine-readable error codes. The frontend branches on these, not on messages. */
export enum ErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  MALFORMED_REQUEST = 'MALFORMED_REQUEST',

  UNAUTHENTICATED = 'UNAUTHENTICATED',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  TOKEN_INVALID = 'TOKEN_INVALID',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  TOKEN_REUSED = 'TOKEN_REUSED',
  ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',
  ACCOUNT_INACTIVE = 'ACCOUNT_INACTIVE',
  EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED',

  FORBIDDEN = 'FORBIDDEN',
  INSUFFICIENT_PERMISSIONS = 'INSUFFICIENT_PERMISSIONS',
  MEMBERSHIP_INACTIVE = 'MEMBERSHIP_INACTIVE',
  TENANT_ACCESS_DENIED = 'TENANT_ACCESS_DENIED',
  SCHOOL_INACTIVE = 'SCHOOL_INACTIVE',

  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  DUPLICATE_RESOURCE = 'DUPLICATE_RESOURCE',
  RELATED_RESOURCE_MISSING = 'RELATED_RESOURCE_MISSING',

  RATE_LIMITED = 'RATE_LIMITED',
  PAYLOAD_TOO_LARGE = 'PAYLOAD_TOO_LARGE',

  INTERNAL_ERROR = 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
}
