/** Canonical audit action names: `<entity>.<verb>`, past tense where it reads better. */
export const AUDIT_ACTIONS = {
  // Authentication
  AUTH_LOGIN_SUCCEEDED: 'auth.login.succeeded',
  AUTH_LOGIN_FAILED: 'auth.login.failed',
  AUTH_LOGOUT: 'auth.logout',
  AUTH_LOGOUT_ALL: 'auth.logout_all',
  AUTH_TOKEN_REFRESHED: 'auth.token.refreshed',
  AUTH_TOKEN_REUSE_DETECTED: 'auth.token.reuse_detected',
  AUTH_SCHOOL_SWITCHED: 'auth.school.switched',
  AUTH_PASSWORD_CHANGED: 'auth.password.changed',
  AUTH_PASSWORD_RESET_REQUESTED: 'auth.password.reset_requested',
  AUTH_PASSWORD_RESET_COMPLETED: 'auth.password.reset_completed',
  AUTH_EMAIL_VERIFIED: 'auth.email.verified',
  AUTH_ACCOUNT_LOCKED: 'auth.account.locked',

  // Tenant lifecycle
  SCHOOL_REGISTERED: 'school.registered',
  SCHOOL_UPDATED: 'school.updated',
  SCHOOL_SETTINGS_UPDATED: 'school.settings.updated',

  // Users and access
  USER_INVITED: 'user.invited',
  USER_INVITATION_ACCEPTED: 'user.invitation.accepted',
  USER_UPDATED: 'user.updated',
  USER_ROLE_CHANGED: 'user.role.changed',
  USER_SUSPENDED: 'user.suspended',
  USER_REACTIVATED: 'user.reactivated',
  USER_ACCESS_REVOKED: 'user.access.revoked',
  ROLE_CREATED: 'role.created',
  ROLE_UPDATED: 'role.updated',
  ROLE_DELETED: 'role.deleted',
  ROLE_MEMBERS_REASSIGNED: 'role.members.reassigned',
  ROLE_PERMISSIONS_UPDATED: 'role.permissions.updated',

  // Academics
  ACADEMIC_SESSION_CREATED: 'academic_session.created',
  ACADEMIC_SESSION_UPDATED: 'academic_session.updated',
  ACADEMIC_SESSION_DELETED: 'academic_session.deleted',
  ACADEMIC_SESSION_SET_CURRENT: 'academic_session.set_current',
  TERM_CREATED: 'term.created',
  TERM_UPDATED: 'term.updated',
  TERM_DELETED: 'term.deleted',
  TERM_SET_CURRENT: 'term.set_current',
  CLASS_CREATED: 'class.created',
  CLASS_UPDATED: 'class.updated',
  CLASS_DELETED: 'class.deleted',
  CLASS_ARM_CREATED: 'class_arm.created',
  CLASS_ARM_UPDATED: 'class_arm.updated',
  CLASS_ARM_DELETED: 'class_arm.deleted',

  // Phase 1+ domains (names reserved so log queries stay stable)
  STUDENT_CREATED: 'student.created',
  STUDENT_UPDATED: 'student.updated',
  STUDENT_DEACTIVATED: 'student.deactivated',
  STUDENT_DELETED: 'student.deleted',
  STUDENT_BULK_IMPORTED: 'student.bulk_imported',
  STUDENT_PROMOTED: 'student.promoted',
  STUDENT_GRADUATED: 'student.graduated',
  GUARDIAN_CREATED: 'guardian.created',
  GUARDIAN_UPDATED: 'guardian.updated',
  GUARDIAN_DELETED: 'guardian.deleted',
  GUARDIAN_LINKED: 'guardian.linked',
  GUARDIAN_LINK_UPDATED: 'guardian.link_updated',
  GUARDIAN_UNLINKED: 'guardian.unlinked',
  FEE_CATEGORY_CREATED: 'fee_category.created',
  FEE_CATEGORY_UPDATED: 'fee_category.updated',
  FEE_CATEGORY_DELETED: 'fee_category.deleted',
  FEE_STRUCTURE_CREATED: 'fee_structure.created',
  FEE_STRUCTURE_UPDATED: 'fee_structure.updated',
  FEE_STRUCTURE_PUBLISHED: 'fee_structure.published',
  FEE_STRUCTURE_ARCHIVED: 'fee_structure.archived',
  FEE_STRUCTURE_DELETED: 'fee_structure.deleted',
  FEE_ASSIGNED: 'fee.assigned',
  FEE_DISCOUNTED: 'fee.discounted',
  FEE_WAIVED: 'fee.waived',
  FEE_CANCELLED: 'fee.cancelled',
  PAYMENT_RECORDED: 'payment.recorded',
  PAYMENT_VERIFIED: 'payment.verified',
  PAYMENT_REJECTED: 'payment.rejected',
  PAYMENT_REMINDERS_SENT: 'payment.reminders_sent',
  RESULT_CREATED: 'result.created',
  RESULT_SUBMITTED: 'result.submitted',
  RESULT_APPROVED: 'result.approved',
  RESULT_PUBLISHED: 'result.published',
  RESULT_RETURNED: 'result.returned',
  SCORES_SAVED: 'scores.saved',
  SUBJECT_CREATED: 'subject.created',
  SUBJECT_UPDATED: 'subject.updated',
  SUBJECT_DELETED: 'subject.deleted',
  CLASS_SUBJECT_ADDED: 'class_subject.added',
  CLASS_SUBJECT_REMOVED: 'class_subject.removed',
  TEACHER_ASSIGNED: 'teacher.assigned',
  TEACHER_UNASSIGNED: 'teacher.unassigned',
  ASSESSMENT_SCHEME_UPDATED: 'assessment_scheme.updated',
  GRADING_SCALE_UPDATED: 'grading_scale.updated',
  ATTENDANCE_TAKEN: 'attendance.taken',
  PORTAL_INVITED: 'portal.invited',
  PORTAL_REVOKED: 'portal.revoked',
  PORTAL_PAYMENT_SUBMITTED: 'portal.payment_submitted',
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];
